### ISSUE TITLE
info about the code

### ISSUE THREAD

**Issue by ily-R** [tn1031/set-matching-pytorch#10]
Hello,

this is not an issue, I just wanted to understand the forward pass, can you please tell me what do the argument represent and what are there expected shapes in this snippet in set_matching.py? 

```
    def forward(self, x, x_mask, y, y_mask):
        x = self.embed_reshape_transpose(x)
        y = self.embed_reshape_transpose(y)
        score = self.apply_enc_dec(x, x_mask, y, y_mask)
        return score
```

**Comment by tn1031** [comment]
Hi @ily-R ,
`x, y` are subsets; one set is divided into two to obtain `x` and `y`. The shape is (B, N, C, H, W) if the `self.embedder` is a CNN and (B, N, 4096) if it is Linear, where B is the mini-batch size and N it the number of elements in the subset.
`x_mask, y_mask` are bool type tensors of size (B, N). Each `x, y` element with the value False is ignored.
